### ISSUE TITLE
Mounting single files into the guest

### ISSUE THREAD

**Issue by jandubois** [AkihiroSuda/lima#130]
I would like to extend `mounts` in 2 ways:

1. Allow different host and guest locations
2. Allow mounting single files instead of directories

The first seems easy enough, but it is not clear to me if this is going to work with sshfs. Also given that #118 is WIP, this may be wasted effort (unless it is rather simple to implement).

Any hints of making single file mounts work with sshfs? ANd if not, will those be possible with samba?

One use case (I have others) would be adding custom CA certs to the guest:

```yaml
mounts:
- host: ~/company/root.crt
  guest: /usr/local/share/ca-certificates/company.crt
  writable: false
provision:
- mode: system
  script: |
    #!/bin/bash
    update-ca-certificates
```

I guess I would like to have something similar to the capabilities of the docker `-v` option to define mounts.

**Comment by AkihiroSuda** [comment]
> Any hints of making single file mounts work with sshfs? And if not, will those be possible with samba?

Unlikely.

The straightforward way would be to just mount the directory of the file from macOS to Linux, and set up Linux bind-mount inside the guest.

**Comment by AkihiroSuda** [comment]
For small files like certificates, I'd suggest just copying the file rather than mounting.

**Comment by MnrGreg** [comment]
The certificate injection use case must be quite common. It would be great if a workable solution could be found to programmatically add certificates on start. nerdctl has a number of issue related to this:
https://github.com/containerd/nerdctl/issues/427
https://github.com/containerd/nerdctl/issues/278
https://github.com/containerd/nerdctl/issues/363

Adding the below to the lima.yml has two issues:

```yaml
mounts:
  - location: "/usr/local/share/ca-certificates"
    writable: false

provision:
  - mode: system
    script: |
      #!/bin/bash
      update-ca-certificates
```

1. provisioning commands (update-ca-certificates) seem to execute before the mounts.
2. mounts don't seem overwrite existing lima VM directories and /usr/local/share/ca-certificates exists in most OSs.
